### ISSUE TITLE
Set Months only, and Years only

### ISSUE THREAD

**Issue by rayflores** [calendariofx/calendario#11]
Looking for an option to show only certain months... for example 1-6, and NOT 7-12?    same with years:  2016 and 2017 only... or only show current year?  as well as to NOT allow to go into 2018+  and -2016  ?    similar to datepicker yearRange

**Comment by deviprsd** [comment]
There is no such option but you can do it, like you can go through a check before calling `$('#calendar').calendario('gotoNextMonth', callback);`

**Comment by rayflores** [comment]
so use the callback as the max so that gotoNextMonth does not exceed?  do I understand that correctly?

**Comment by deviprsd** [comment]
Kind of but before the callback is called the calendar is already generated. So check the month and before you call the gotoNextMonth function. Check the month and year by using these utility functions, `$('#calendar').calendario('getMonth')` and `$('#calendar').calendario('getYear')`.

**Comment by rayflores** [comment]
ok.  thank you :)
