### ISSUE TITLE
two labels same day

### ISSUE THREAD

**Issue by rayflores** [calendariofx/calendario#12]
is there a way to add a foreach to the labels presented 'per day' ?  i do not see an example in your demo, and when I run it currently, there is only the 'last' entry for that day that shows...

**Comment by rayflores** [comment]
here is my caldata: 
`caldata : {'05-01-2016':'10am to 8pm','05-01-2016':'10am to 6pm','05-02-2016':'10am to 8pm','05-03-2016':'4pm to 8pm'}`

as you can see, 05-01-2016 is twice, but displayed is only second label..

**Comment by deviprsd** [comment]
Multiple events on the same day feature has been added since v2. The details are in the old, and not maintained repo, as this was created by codrops. The format should be this.

``` javascript
caldata : {
    '05-01-2016':[
        {content: '10am to 8pm'},
        {content: '10am to 6pm'},
    ],
    '05-02-2016':'10am to 8pm',
    '05-03-2016':'4pm to 8pm'
}
```

**Comment by rayflores** [comment]
thank you.

**Comment by deviprsd** [comment]
In multiple events, wrapping them up in objects is compulsory. You can refer to https://github.com/codrops/Calendario and the [dataTimeline.js](https://github.com/deviprsd21/Calendario/blob/master/js/dataTimeline.js) for more info.

**Comment by deviprsd** [comment]
May I make a suggestion? If you are making a timeline kind of thing, refer to this, http://deviprsd21.github.io/Calendario/index3.html :smile:

**Comment by rayflores** [comment]
not a timeline... but just a calendar... with backend settings... wp plugin... http://floressquad.com/customers/testing/sample-page/

**Comment by deviprsd** [comment]
![2016-02-23](https://cloud.githubusercontent.com/assets/3809354/13232043/60079cbc-d9d3-11e5-9fba-05d2698aee01.png)
Looks like the month and year are in the wrong place.

**Comment by rayflores** [comment]
css... no worries.... page width...

**Comment by deviprsd** [comment]
All the best. Ping back, if you need more help. Close this issue if you are done with your problems. Thanks for creating a plugin, share it with me when you are done.

**Comment by rayflores** [comment]
you bet... thanks for your guidance... big help thus far ;)

**Comment by rayflores** [comment]
Hey Devi - just wanted to show you the end product of the plugin I built: http://www.newforestwaterpark.co.uk/opening-times/wake-park-opening-times/

i started a repo here as well:  https://github.com/rayflores/wp-calendario

**Comment by deviprsd** [comment]
Cool, I'll mention in the docs. Version 6 is underway please take a look at the wikis for what I plan to change in version 6.

**Comment by deviprsd** [comment]
Hey,check this, scroll down :smile: https://github.com/deviprsd21/Calendario/blob/master/README.md

**Comment by rayflores** [comment]
Ha!  that's awesome!  thanks for the mention :+1:
