### ISSUE TITLE
Events are not properly listed under their stated date

### ISSUE THREAD

**Issue by ppapadatis** [calendariofx/calendario#13]
Hi,
I've been using your plugin and found a weird issue. I wasn't able to track down completely the problem, but I hope I'll guide you through my findings.

I set two events, the first one with a starting day on **11-01-2016** and an ending day on **11-02-2016** and the second on with a starting day on **12-02-2016** and and ending day on **12-02-2016**.

The problem is that both events are shown both on their months and each others. Additionally, the first event is still rendered in December even though there is no indication in the html.

The data.js file:
![data](https://cloud.githubusercontent.com/assets/5330923/13470688/f53d163e-e0b5-11e5-9e90-486453280b80.jpg)

The calendar is shown correctly ...
![calendar](https://cloud.githubusercontent.com/assets/5330923/13470739/2d1a67e6-e0b6-11e5-8f57-d31a0a2f10e6.JPG)

... but on November 2nd, there are 2 events
![2-nov](https://cloud.githubusercontent.com/assets/5330923/13470747/3526c056-e0b6-11e5-9f61-bef3cc8969cd.JPG)

also in December 2nd, 2 events
![2-dec](https://cloud.githubusercontent.com/assets/5330923/13470751/38ba0caa-e0b6-11e5-9c20-ed4722be0e4c.JPG)

and a non-existent event in December 1st
![1-dec](https://cloud.githubusercontent.com/assets/5330923/13470755/3b8e7fc4-e0b6-11e5-9865-660b2c3819e9.JPG)

What I've found is that you set and search **curData** based on the numeric date. This leads to a problem for non-unique indices, thus setting the same event (or another one) on a wrong date.

**Comment by deviprsd** [comment]
I did encounter such problems while updating to the latest version, and if I remember I did fix this problem. Can you make sure that you are using the latest version?

**Comment by ppapadatis** [comment]
Yes, I do use the latest version (5.0.0) and the problem is still there.

**Comment by deviprsd** [comment]
Fixing this will take time, Downgrade back to 4.1.0, Thanks for informing this is a very buggy version.
