### ISSUE TITLE
MultiDays Events

### ISSUE THREAD

**Issue by fernando1355** [calendariofx/calendario#16]
Hi there,

I need to add some events which lasts more than one day, I need to block an interval of days with DateStart and DateEnd of the event, is that possible?

Thanks!

**Comment by KoniKodes** [comment]
Check out the data.js file. You should be able to have your event date as the start date and the end date inside the comment section.

**Comment by deviprsd** [comment]
Sorry for the late reply, in the new versions if you want a block of events make sure to use `repeat: 'INTERVAL'`. Here is an example!

``` javascript
'03-02-2015' : [{content : 'Graduation Exams', repeat: 'INTERVAL', allDay: true, endDate: '03-20-2015'}]
```
