### ISSUE TITLE
bug on IE

### ISSUE THREAD

**Issue by Mathieu44** [calendariofx/calendario#17]
there are a bug on IE, the last colone (sunday) is not display. Exemple :

IE Calendar  :
mond | tue | wed | thu | fri | sat | sun  
1            2      3        4     5     6
7            8      9       10    11   12
13         14    15

chrome calendar :

mond | tue | wed | thu | fri | sat | sun  
1            2      3        4     5     6      7
8            9      10      11  12   13     14
15

**Comment by deviprsd** [comment]
Can, you send a screenshot?

**Comment by Mathieu44** [comment]
Hello, Thanks for your answer.. I have find your patch after post here, so sorry. Your calendario script is really good.
for people it's here :
https://github.com/codrops/Calendario/commit/a91129e34ac7fd7e429f6d3fe17674d61909642b

**Comment by pixelzdesign** [comment]
This codrops/Calendario@a91129e stil doesn't work in IE and Edge.
I find solution. Thanx frxnz.
