### ISSUE TITLE
Events on the same date of the previous and current month are rendered in the same day

### ISSUE THREAD

**Issue by mityakoval** [calendariofx/calendario#20]
I will just post some screenshots because this issue is quite hard to explain.

![screen shot 2016-12-13 at 12 36 02](https://cloud.githubusercontent.com/assets/10942685/21138987/01486ff8-c131-11e6-9690-af905bfd92d5.png)
![screen shot 2016-12-13 at 12 36 12](https://cloud.githubusercontent.com/assets/10942685/21138989/049fbb8e-c131-11e6-9d35-8b1fc612c53a.png)

And this is the output from the console at the time of rendering: 
This is December. As you can see it has 8 events in total for the first day of the month - 4 events for Dec 1 and another 4 for Jan 1. However, all 8 are placed on Jan 1.

<img width="221" alt="screen shot 2016-12-13 at 12 39 37" src="https://cloud.githubusercontent.com/assets/10942685/21139039/40344890-c131-11e6-9e4e-99e7ac03a519.png">

I double checked my backend to return correct data.

**Comment by deviprsd** [comment]
I will need more data to understand what is happening, can you provide me with a link to this project of yours or something?

**Comment by mityakoval** [comment]
@deviprsd21 I have sent you the link and credentials to deviprsd21@gmail.com

**Comment by mityakoval** [comment]
@deviprsd21 You can see actual events on a certain day by clicking on it.

**Comment by deviprsd** [comment]
![2016-12-13 3](https://cloud.githubusercontent.com/assets/3809354/21140657/59148d56-c15f-11e6-8529-3fb26e83b36c.png)
I'm testing your backend data with Calendario v5.0.1 (Released a long time ago) and this is the result. And that is the month of December with Jan 1st as it's last date.

**Comment by mityakoval** [comment]
OK. So it's probably my code. Any ideas what might be causing such behaviour? Because I have changed the implementation a little bit. But I've compared `Calendario.prototype.parseDay` and `Calendario.prototype.parseDataToDay` functions to my code and they are the same.

**Comment by deviprsd** [comment]
It seems you have made some changes with original js file, do look into it. And I can't seem to think why it is happening with you without knowing what changes you have made so far. Also this looks similar to #13, Look into that too

**Comment by mityakoval** [comment]
@deviprsd21 Replaced my code with the original and still the same problem. Just to be sure that the server sends correct data: 

![screen shot 2016-12-13 at 14 15 20](https://cloud.githubusercontent.com/assets/10942685/21141665/be5649dc-c13e-11e6-83cb-e155e0f1b085.png)

**Comment by deviprsd21** [comment]
I'm just unable to reproduce your issue in the fresh clone of this repo.

**Comment by deviprsd** [comment]
Looks like I'm able to reproduce it. I will look into it.

**Comment by deviprsd** [comment]
Let me know if this worked and give some suggestions for v6 in which way I can make Calendario life more rich and easier

**Comment by mityakoval** [comment]
Updated my code with your commit. The issue is fixed for the next month but it is still there for the current month. 

![screen shot 2016-12-13 at 15 37 39](https://cloud.githubusercontent.com/assets/10942685/21144228/24d976ba-c14a-11e6-90b2-7df5daff9e05.png)

It still displays events from Nov 30 on Dec 30

**Comment by deviprsd** [comment]
This should completely fix everything.

**Comment by mityakoval** [comment]
Awesome! Works for me. Thank you! :)
