### ISSUE TITLE
Interval Event on the fly replace Others Interval Events already added

### ISSUE THREAD

**Issue by Vallevard** [calendariofx/calendario#21]
Hi,
When I tried to add a new event with the repeat: 'INTERVAL' option  using the function 'setData', It replaces all events that has 'INTERVAL' option, no matter what date, even when it's not the current month.
Could you tell me if you are able to reproduce the issue?
Thanks.
**version:** 5.0.1
**Notes:** 

- Adding an event that does not use this option works but if it has more that one option it doesn't work too.
- It looks like it occurs also 'MONTHLY' option.

**Comment by deviprsd** [comment]
I'll look into it

**Comment by deviprsd** [comment]
I didn't have time to look into it but will do it by January 31st, thanks for having patience.
