### ISSUE TITLE
There is no clear license

### ISSUE THREAD

**Issue by cpba** [calendariofx/calendario#22]
There's a section labelled "Licensing & Terms of Use" at the bottom of "README.md" but it doesn't link to any actual software license, only some rather ambiguous guidelines.

Please add a license, or otherwise clearly state that this is proprietary software.

**Comment by deviprsd** [comment]
I forked the project from codrops/Calendario after taking permission from them and didn't bother to add one and not going to since I'm thinking of deprecating this in favor CalendarioFX which will be more advanced version of it.
