### ISSUE TITLE
Tried to Upgrade to Responsive and jQuery Error

### ISSUE THREAD

**Issue by KoniKodes** [calendariofx/calendario#26]
Hi,
I tried to use the upgrade for responsive and I am not sure what I did wrong, but this is the error:
jquery.min.js:2 Uncaught TypeError: Cannot use 'in' operator to search for 'length' in New Year's Eve<span><br/>Have a Safe and Happy New Year's Eve!</span>
    at s (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at String.<anonymous> (jquery.calendario.js:121)
    at Function.each (jquery.min.js:2)
    at Calendario.processCaldata (jquery.calendario.js:120)
    at Calendario.init (jquery.calendario.js:48)
    at new Calendario (jquery.calendario.js:9)
    at HTMLDivElement.<anonymous> (jquery.calendario.js:405)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)

Right now all I have a blank page. Your help is greatly appreciated.

**Comment by KoniKodes** [comment]
I am still having this error. Can someone help me please?

**Comment by deviprsd** [comment]
I have to look at your event data to help you out.

**Comment by KoniKodes** [comment]
Thank you. How can I get that to you?

Toni

**Comment by deviprsd** [comment]
Paste it here.

**Comment by KoniKodes** [comment]
[hi-data.zip](https://github.com/CalendarioFX/Calendario/files/1354336/hi-data.zip)

**Comment by KoniKodes** [comment]
Thank you.
Did not mean to close. It is still an issue.
I appreciate your help.

**Comment by deviprsd** [comment]
Can you try to follow this format for your events as shown here, https://github.com/CalendarioFX/Calendario/blob/master/js/data.js. Then let me know if it works on not.

**Comment by KoniKodes** [comment]
I found the script name changed from src="js/calendario.min.js to src="js/jquery.calendario.min.js. When I fixed my html to reflect that, I received this message:

~prev-hi-cal.html.htm:1 Refused to execute script from 'https://raw.githubusercontent.com/codrops/Calendario/master/js/update.js?_=1508696607847' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by deviprsd** [comment]
When you are initializing the calendar, add `checkUpdate` and set it to `false`. Like how it is shown here https://github.com/CalendarioFX/Calendario/blob/61bfbc0d53087b00de49586bfd64ce9f26a6336e/index.html#L71

**Comment by KoniKodes** [comment]
This is perfect! Thank you so much!
You can see my calendar [here](http://konikodes.com/calendar/hi-cal.html)
