### ISSUE TITLE
How to put color depending on category

### ISSUE THREAD

**Issue by BeingCreativeUs** [calendariofx/calendario#28]
Hi! I want to color the days if there's an event. I attach a example of what I want.

![screenshot_3](https://user-images.githubusercontent.com/28728339/32561298-475eaa5a-c4ac-11e7-8c11-05e535b947dc.png)

I see that when you put a date on data.js, the category class goes to the span of the event title, but I would like to have that class on the day too (where appears fc-content).

Is it possible? If yes, please, explain me how to do it because I don't have too much experience on JS.

Thank you.

**Comment by deviprsd** [comment]
Refer, https://github.com/CalendarioFX/Calendario/issues/15#issuecomment-218083161
