### ISSUE TITLE
Wrong month returned

### ISSUE THREAD

**Issue by JustasKuizinas** [calendariofx/calendario#3]
I have calendario showing october month, it also shows some November days, but when I use onDayClick.calendario event and click on November first, "dateprop" returns:
`data: Object
day: "1"
month: 10
monthname: "Oct"
weekday: 7
weekdayname: "Sunday"
year: 2015`

it should retrun:
`data: Object
day: "1"
month: 11
monthname: "Nov"
weekday: 7
weekdayname: "Sunday"
year: 2015`

**Comment by deviprsd** [comment]
What version of Calendario are you using?

**Comment by JustasKuizinas** [comment]
I use 4.1.0

**Comment by deviprsd** [comment]
My test shows something different,
![x](https://cloud.githubusercontent.com/assets/3809354/10307008/adcbedc0-6c48-11e5-967c-0eb311d0f1f4.png)

**Comment by JustasKuizinas** [comment]
I will attach screenshots below to see where is the bug.

![2015-10-06 15_43_11](https://cloud.githubusercontent.com/assets/5862640/10308822/2d5bdb52-6c41-11e5-9a08-9fef44fcafd2.png)
![2015-10-06 15_42_09](https://cloud.githubusercontent.com/assets/5862640/10308823/2d7e85da-6c41-11e5-99aa-d235be8a26d9.png)

**Comment by deviprsd** [comment]
You seem to have modified a lot, do you mind if I could take a look at your apps code and figure out the problem?

**Comment by JustasKuizinas** [comment]
Well it's not the app problem because I haven't modified your js library it's problem with calendario js.

**Comment by JustasKuizinas** [comment]
You cant test it here just open console. 
http://webapps.lt/demo/calendario-bug/planner.php

**Comment by deviprsd** [comment]
Okay, I better go through it!

## 

Sent from Bòźi Dâbèl

**Comment by deviprsd** [comment]
Bug Fixed :smile:, get the update!
