### ISSUE TITLE
Week day name bug

### ISSUE THREAD

**Issue by jamie-nxtgencare** [calendariofx/calendario#31]
Retrieving the week day name for a date on a Saturday always returns Sunday. This is because of a bad bug fix from 5 years ago:

https://github.com/codrops/Calendario/commit/0977d07178e5f1b818795e309709309d2340eb1a

The bug fixed reads: 

> Fixed small bug on line 81. dateProp.weekdayname would be undefined if it's sunday (idx+self.options.startIn would be 7 and thus the options.weeks array would return undefined)

While they are correct if self.options.startln is 1, if you don't set that to 1, then you move Saturday to Sunday needlessly. This line should be:

`'weekdayname' : self.options.weeks[($(this).index() + self.options.startIn) % 7],`

**Comment by deviprsd** [comment]
Looks good, I'll do a little bit more test and merge the pull request.

**Comment by jamie-nxtgencare** [comment]
👍
