### ISSUE TITLE
Calendar INTERVAL, WEEKDAYS, ... doesn't work when update jQuery to ver. 3.3.1

### ISSUE THREAD

**Issue by pixelzdesign** [calendariofx/calendario#33]
Only day events works, when I put for repeat INTERVAL, WEEKDAYS, ... events doesn't appear in calendar.
How to solve this to work with jQuery ver. 3.3.1
EDIT: It's work.
I use Laravel and can't make to work INTERVALS. Only work MONTHLY

**Comment by deviprsd** [comment]
I probably won't support jQuery 3. My current plans are to move this to ESM, IIFE and CJS formats so they can be used in multiple platforms. You won't require jQuery in the future to use Calendario
