### ISSUE TITLE
5.0.2 BUG for repeat: MONTHLY and INTERVAL

### ISSUE THREAD

**Issue by pixelzdesign** [calendariofx/calendario#35]
1. Event
`'01-07-2018' : [{content: 'Monthly And Yearly', repeat: 'MONTHLY', allDay: true, endDate: '02-07-2019'}],`
not work MONTHLY (work as YEARLY). The event is shown only on January 1, 2018 and January 1, 2019.

2. When I put an event that goes over the next month:
`'03-02-2018' : [{content : 'Graduation Exams', repeat: 'INTERVAL', allDay: true, endDate: '04-20-2018'}],`
show the events in the first month March (03), but not in another April (04).

This events work good and as expected in 5.0.0 and 5.0.1 version.

**Comment by pixelzdesign** [comment]
Now it's working for v5.0.2

**Comment by deviprsd** [comment]
Please make a pr and I'll merge it
