### ISSUE TITLE
Current day feature

### ISSUE THREAD

**Issue by JustasKuizinas** [calendariofx/calendario#5]
For example today is 2015-10-31. October 31 block have class fc-today, but when you switch to the next month 2015-11, October 31 dont have class fc-today.

Check this link:
http://webapps.lt/demo/calendario-bug/planner.php

**Comment by deviprsd** [comment]
I wouldn't say it as bug, because this functionality was never added. I never really thought of it, so I will take it as a feature request!

**Comment by deviprsd** [comment]
@JustasKuizinas I have almost added this feature, but I'm not able to decide whether this kind of date, i.e. the emptydates, to contain the event details, I think it would be good to just show the fc-today class and not its event details as it might destroy the purpose of the name emptydate. What do you think?

**Comment by JustasKuizinas** [comment]
Well you are correct, but it would be nice to have events on previous/next month days. Dont know how much people need this funcionality but for example I need it in my project :)

**Comment by deviprsd** [comment]
I have to then test the performance before including this feature!
