### ISSUE TITLE
Previous and Next Month

### ISSUE THREAD

**Issue by nishadotcom** [calendariofx/calendario#7]
Hai @deviprsd21 

I like to push my code into a branch. I think that would be better.
Could please create a new branch for it and let me know the name?

Best,
Real Infotech Services
nisha.com126@yahoo.com

**Comment by nishadotcom** [comment]
Hai @deviprsd21!

The new build has the functionality. You have done it.

You can check the old and new new for proof.
![calo](https://cloud.githubusercontent.com/assets/15242739/11202616/f723762c-8d0f-11e5-9efb-7365f9191953.png)
![cal](https://cloud.githubusercontent.com/assets/15242739/11202618/fdba7a08-8d0f-11e5-8b6f-cd1372ad01ef.png)

Thanks.

Best,
Real Infotech Services,
 nisha.com126@yahoo.com

**Comment by deviprsd** [comment]
So you won't be pushing your code?

**Comment by nishadotcom** [comment]
It is my pleasure to push it. I will do and let you know asap.

Best,
Real Infotech Services,
nisha.com126@yahoo.com

**Comment by nishadotcom** [comment]
Hai @deviprsd21 

I get the following error on push command
![erro](https://cloud.githubusercontent.com/assets/15242739/11236768/bb8b93fe-8e01-11e5-8c57-bec1016366a7.png)

Best,
Real Infotech Services,
nisha.com126@yahoo.com
