### ISSUE TITLE
Full page in a container with a fixed width and height

### ISSUE THREAD

**Issue by ken-colvin** [calendariofx/calendario#8]
Hi - Love your calendar. I really want to use your full page calendar but I can not figure out how to change the css to be in a container of fixed width and height.

Can you give an example using the (Full Page) calendar but have it be in a container whose width is 400px and height 300px

Full page being http://deviprsd21.github.io/Calendario/

**Comment by deviprsd** [comment]
You mean the calendar will be wrapped in a container whose dimensions is 400x300, like a mobile device?.

**Comment by ken-colvin** [comment]
Any div of any dimension.  For example, 800x600, 400x300,  600x600, ... Basically I want to define the fixed width and height of the div:

Scenario: 1 calendar whose width is 800 and height 600

``` html
<div class='row'>
   <div class=col-md-12 style='width:800px; height:600px'></div>
</div>
```

Scenario: 2 calendars in 1 row and 2 columns of equal dimensions

``` html
<div class='row'>
   <div class=col-md-6 style='width:400px; height:300px'>Calendar 1</div>
   <div class=col-md-6 style='width:400px; height:300px'>Calendar 2</div>
</div>
```

**Comment by ken-colvin** [comment]
Sorry, accidentally clicked Close ...

**Comment by deviprsd** [comment]
`class` attributes value should be wrapped around quotes, and it seems you are using bootstraps grid, don't used fixed dimensions on them, they are meant to  be responsive. You can find your answer in **calendar.css**, see `.fc-calendar-container`. Find the same thing in **custom_1.css**

**Comment by deviprsd** [comment]
I hope your problems have been fixed!
