### ISSUE TITLE
Remove time from cells/calendar

### ISSUE THREAD

**Issue by RedNan** [calendariofx/calendario#9]
I am pretty much a complete beginner. I don't even know what to search Google for!
I updated from  jquery.calendario.js v1.0.0 to:  jquery.calendario.js v3.2.0 and added jquery.calendario.min.js.

I really need to get rid of the time in each calendar cell. I'm sure this is drop dead simple, but I just can't seem to find the solution.

I'll keep trying...
Thank you.

**Comment by deviprsd** [comment]
Like hiding it or completely removing it?

**Comment by RedNan** [comment]
Either. Just so long as it does not show on the calendar.

**Comment by deviprsd** [comment]
Oh, then it is good to have the time tags. Just use css to remove them. Search in google, `display: none;` and in this way you will learn something

**Comment by RedNan** [comment]
HA!
Yes, display:none I quite understand!

It's where to PUT display:none that I find difficult!

However, you mention css, so I can forget all other and focus there.

## Thank you.

Nancy Cardinali
415-717-7913 - cell
Nancy@CardinaliDesigns.com
www.CardinaliDesigns.com
Web & Graphic Design

```





> Devi Prasad <mailto:notifications@github.com>
> January 4, 2016 at 10:53 AM
>
> Oh, then it is good to have the time tags. Just use css to remove 
> them. Search in google, |display: none;| and in this way you will 
> learn something
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/deviprsd21/Calendario/issues/9#issuecomment-168767737>.
>

```
